# Generated by Django 6.0.2 on 2026-03-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0003_rename_code_ticket_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
    ]
