# Generated by Django 6.0.3 on 2026-03-30 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0005_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Number plate must be in format: ABC-123DE', regex='^[A-Za-z]{3}-\\d{3}-[A-Za-z]{2}$')]),
        ),
    ]
