# Generated by Django 6.0.3 on 2026-03-31 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0006_alter_vehicle_number_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Number plate must be in format: ABC-123-DE', regex='^[A-Za-z]{3}-\\d{3}-[A-Za-z]{2}$')]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='park_system.parkingslot'),
        ),
    ]
