# Generated by Django 6.0.3 on 2026-03-31 22:28

from django.db import migrations

def create_parking_slots(apps, schema_editor):
    ParkingSlot = apps.get_model('park_system', 'ParkingSlot')
    ParkingSlot.objects.bulk_create([
        ParkingSlot(slot_number=i, is_occupied=False)
        for i in range(1, 201)  # creates 200 slots
    ])

def delete_parking_slots(apps, schema_editor):
    ParkingSlot = apps.get_model('park_system', 'ParkingSlot')
    ParkingSlot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0007_parkingslot_alter_vehicle_number_plate_ticket_slot'),
    ]

    operations = [
        migrations.RunPython(create_parking_slots, delete_parking_slots),
    ]
