# Generated by Django 6.0.3 on 2026-03-31 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0008_populate_parking_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='park_system.parkingslot'),
        ),
    ]
