# Generated by Django 6.0.3 on 2026-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0009_alter_ticket_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
