# Generated by Django 6.0.3 on 2026-04-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0010_ticket_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fee',
            new_name='amount',
        ),
    ]
