# Generated by Django 6.0.3 on 2026-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0012_ticket_overdue_ticket_overdue_since_vehicle_flagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
