# Generated by Django 6.0.3 on 2026-04-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0013_ticket_paid_at_ticket_payment_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('exit_time__isnull', True)), fields=('vehicle',), name='unique_active_ticket_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('exit_time__isnull', True)), fields=('slot',), name='unique_active_ticket_per_slot'),
        ),
    ]
