# Generated by Django 6.0.3 on 2026-04-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0014_ticket_unique_active_ticket_per_vehicle_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('exit_time__isnull', True), models.Q(('amount__isnull', False), ('exit_time__isnull', False)), _connector='OR'), name='exit_time_requires_amount'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status', False), models.Q(('amount__isnull', False), ('exit_time__isnull', False), ('payment_status', True)), _connector='OR'), name='valid_payment_state'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('payment_status', True), _negated=True), name='paid_ticket_must_have_amount'),
        ),
    ]
