# Generated by Django 6.0.3 on 2026-04-24 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0015_ticket_exit_time_requires_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('session_started', 'Session Started'), ('session_closed', 'Session Closed'), ('payment_recorded', 'Payment Recorded'), ('fee_overridden', 'Fee Overridden'), ('vehicle_flagged', 'Vehicle Flagged'), ('vehicle_unflagged', 'Vehicle Unflagged'), ('vehicle_activated', 'Vehicle activated'), ('vehicle_disactivated', 'Vehicle disactivated'), ('vehicle_added', 'Vehicle Added'), ('vehicle_deleted', 'Vehicle Deleted'), ('vehicle_flagged_auto', 'Vehicle Flagged (Automatic)'), ('ticket_reopened', 'Ticket Reopened'), ('role_changed', 'Role Changed'), ('customer_registered', 'Customer Registered')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('attendant', 'Attendant'), ('customer', 'Customer')], default='customer', max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_active_ticket_per_slot',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='exit_time_requires_amount',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='valid_payment_state',
        ),
        migrations.AddField(
            model_name='ticket',
            name='vehicle_exited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_exited', False)), fields=('slot',), name='unique_occupied_slot'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('exit_time__isnull', False), ('amount__isnull', True), _connector='OR'), name='active_ticket_has_no_amount'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('exit_time__isnull', True), ('amount__isnull', False), _connector='OR'), name='closed_ticket_requires_amount'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status', False), models.Q(('amount__isnull', False), ('exit_time__isnull', False)), _connector='OR'), name='valid_payment_state'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('vehicle_exited', False), models.Q(('exit_time__isnull', False), ('payment_status', True)), _connector='OR'), name='exited_requires_payment_and_close'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('vehicle_exited', False), ('exit_time__isnull', False), _connector='OR'), name='exited_requires_closed_session'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='park_system.ticket'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='park_system.vehicle'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='park_system_action_82ae52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by'], name='park_system_perform_39214b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ticket'], name='park_system_ticket__9614ed_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='park_system_timesta_ef935e_idx'),
        ),
    ]
