# Generated by Django 6.0.3 on 2026-04-30 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_system', '0016_auditlog_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('session_started', 'Session Started'), ('session_closed', 'Session Closed'), ('payment_recorded', 'Payment Recorded'), ('payment_initiated', 'Payment Initiated'), ('payment_failed', 'Payment Failed'), ('fee_overridden', 'Fee Overridden'), ('vehicle_flagged', 'Vehicle Flagged'), ('vehicle_unflagged', 'Vehicle Unflagged'), ('vehicle_activated', 'Vehicle activated'), ('vehicle_disactivated', 'Vehicle disactivated'), ('vehicle_added', 'Vehicle Added'), ('vehicle_deleted', 'Vehicle Deleted'), ('vehicle_flagged_auto', 'Vehicle Flagged (Automatic)'), ('ticket_reopened', 'Ticket Reopened'), ('role_changed', 'Role Changed'), ('customer_registered', 'Customer Registered')], max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('paystack_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(default=dict)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='park_system.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
